apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PVC}
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ${MODE}
  nfs:
    path: /${PVC}
    server: ${PRIMARY_IP}
  persistentVolumeReclaimPolicy: Recycle
